server:
  port: 7003
javax:
  sql:
    DataSource:
      personasDataSource:
        dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
        dataSource:
          databaseName: "ejemplo"
          user: "postgres"
          password: "admin"